[tool.poetry]
name = "generative-ai-python-2025-02"
version = "0.1.0"
description = ""
authors = ["JauniusPinelis <JauniusPinelis@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
